### ISSUE TITLE
Rename extension, update assets & documentation

### ISSUE THREAD

**Issue by celanthe** [camunda-community-hub/camunda-cloud-code-studio#13]
Hi Josh and Thomas,

I hope today finds you well! This issue is being opened to ask if you would be open to renaming your extension on GitHub to reference Camunda Platform 8 rather than Camunda Cloud after its release on April 12th, 2022. (For example: camunda-platform-8-code-studio) This change will also likely impact any screenshots you have in the README that reference Camunda BPM or previous versions of Camunda Platform, and this will likely need to also be updated throughout the repo's documentation as a whole. You can also make use of [Shields.io badges](https://github.com/camunda-community-hub/community/blob/main/extension-lifecycle.md) to indicate which version of Camunda your extension is compatible with. 

While it is not a **requirement** that you rename your extension to align with Camunda Platform 8, we would **greatly** appreciate it if you could make these changes, and merge them anytime after April 12th, 2022.

**Comment by Hafflgav** [comment]
Hey @jwulf I just renamed all occurrences in the readme except links and pictures. It is contained in a branch as of now. I would wait till the release next Tuesday before updating these. :)
