### ISSUE TITLE
Describe Camunda Cloud

### ISSUE THREAD

**Issue by jwulf** [camunda-community-hub/camunda-cloud-code-studio#5]
Write a section "Get familiar with Camunda Cloud and discover features" in the README.
(This is referring to exercise to 2)

**Comment by Hafflgav** [comment]
@jwulf I just added a commit to this issue. You can find the updated readme and some pictures already in the main branch. Feel free to review and to fix it right away. 

Do we want to create branches for each of these issues or do you think it is okay and more time efficient to just commit to the master right away?
